# Generated by Django 5.1.7 on 2025-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='selected_seats',
            field=models.ManyToManyField(blank=True, to='travels.seat'),
        ),
    ]
