# Generated by Django 5.1.7 on 2025-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_journey_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
